export const INITIAL_CLIENTS = [
  {
    code: "C001",
    name: "株式会社青葉商会",
    address: "千葉県印西市中央北1-10-5",
    contactTel: "0476-11-3201",
    contactEmail: "aoba@sample-client.jp",
    contactPerson: "青木 恒一",
    remarks: "定期点検案件が中心",
  },
  {
    code: "C002",
    name: "北斗サービス有限会社",
    address: "千葉県成田市花崎町812-4",
    contactTel: "0476-22-4810",
    contactEmail: "hokuto@sample-client.jp",
    contactPerson: "村上 直樹",
    remarks: "月末に納車前仕上げ依頼が集中",
  },
  {
    code: "C003",
    name: "南海トランスポート",
    address: "茨城県龍ケ崎市佐貫3-7-2",
    contactTel: "0297-61-1185",
    contactEmail: "nankai@sample-client.jp",
    contactPerson: "小林 一真",
    remarks: "商用バンの入庫が多い",
  },
  {
    code: "C004",
    name: "東都メンテナンス",
    address: "東京都葛飾区白鳥2-18-9",
    contactTel: "03-5650-4421",
    contactEmail: "toto@sample-client.jp",
    contactPerson: "藤井 美紀",
    remarks: "コーティング補修の定期契約あり",
  },
  {
    code: "C005",
    name: "グリーン自動車販売",
    address: "埼玉県三郷市中央5-14-12",
    contactTel: "048-953-7708",
    contactEmail: "green@sample-client.jp",
    contactPerson: "遠藤 恒一",
    remarks: "展示車両の仕上げ対応あり",
  },
  {
    code: "C006",
    name: "サンライズ物流",
    address: "千葉県船橋市潮見町23-7",
    contactTel: "047-404-9182",
    contactEmail: "sunrise@sample-client.jp",
    contactPerson: "石原 竜也",
    remarks: "早朝引取の案件あり",
  },
  {
    code: "C007",
    name: "ミナト整備センター",
    address: "東京都江東区新木場1-8-6",
    contactTel: "03-3522-6104",
    contactEmail: "minato@sample-client.jp",
    contactPerson: "田所 健",
    remarks: "車検前整備と同時依頼が多い",
  },
  {
    code: "C008",
    name: "高原リース株式会社",
    address: "栃木県宇都宮市平出工業団地14-2",
    contactTel: "028-689-2040",
    contactEmail: "takahara@sample-client.jp",
    contactPerson: "中村 彩",
    remarks: "月次請求案件",
  },
];